config/routes.rb
Rails.application.routes.draw do

  resources :genres

  resource :session

  get 'signin' => 'sessions#new'

  get 'signup' => 'users#new'

  get 'movies/filter/:scope' => 'movies#index', as: :filtered_movies

  resources :users
  
  root "movies#index"
  resources :movies do
  	resources :reviews
  	resources :favorites
  end
end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, :class => "flash #{key}") %>
<% end %>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
	<p>
		Copyright &copy; 2015 CatfriendOnMoviesInc
	</p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
<h1>Catfriend on Movies</h1>
<nav>

</nav>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li>
        <%= link_to 'Released Movies', movies_path %>
      </li>
      <li>
        <%= link_to 'Recent Releases', filtered_movies_path(:recent) %>
      </li>
      <li>
        <%= link_to 'Upcoming Movies', filtered_movies_path(:upcoming) %>
      </li>
      <li>
          <%= link_to 'Movies by Genre', genres_path %>
        </li>
        <li>
          <%= link_to 'Hits', filtered_movies_path(:hits) %>
        </li>
        <li>
          <%= link_to 'Flops', filtered_movies_path(:flops) %>
        </li>
      <li>
        <% if current_user_admin? %>
          <%= link_to 'Add New Movie', new_movie_path%>
        </li>
        <li>
          <%= link_to 'Add New Genre', new_genre_path %>
        <% end %>
      </li>
        <p>
          <li>
      <% if current_user %>
        <%= link_to " Your Account Settings", edit_user_path(current_user) %>
      </li>

      <li>
        <%= link_to 'Sign Out', session_path, method: :delete %>
      </li>
        <li>
        <%= current_user.name + ' is online' %>
      </li>
      <% else %>
        <%= link_to 'Sign Up', signup_path, class: 'button' %>
        <%= link_to 'Sign In', new_session_path, class: 'button' %>
      <% end %>
  </p>
</li>
    </ul>

  </nav>

  <%= content_for(:sidebar) %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<link href='http://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
  <title><%= page_title %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/header" %>

<div id="wrapper">
 
  <%= render "layouts/flashes" %>
  
  <div id="container">
    <section id="sidebar">
      <%= render "layouts/sidebar" %>
    </section>
    <section id="content">
      <%= yield %>
    </section>
  </div>

</div>

<%= render "layouts/footer" %>

</body>
</html>